name: Lint Error 
on: 
  push: 
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get modified files
        uses: dorny/paths-filter@v2
        id: filter
        with: 
          list-files: shell
          filters: |
            py_modified: 
              -added|modified: "./**/*.py"
      - name: setup python
        if: ${{steps.filter.outputs.py_modified == 'true' }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x86
          cache: 'pip'
      - name: install dependencies
        if: ${{steps.filter.output.py_modified == 'true' }}
        run: pip install flake8
      - name: Run flake8
        if: ${{steps.filter.output.py_modified == 'true' }}
        run: flake8 ${{steps.filter.output.py_modified_files }}
